/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: request.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "request.pb-c.h"
void   request_header__init
                     (RequestHeader         *message)
{
  static const RequestHeader init_value = REQUEST_HEADER__INIT;
  *message = init_value;
}
size_t request_header__get_packed_size
                     (const RequestHeader *message)
{
  assert(message->base.descriptor == &request_header__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t request_header__pack
                     (const RequestHeader *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &request_header__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t request_header__pack_to_buffer
                     (const RequestHeader *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &request_header__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RequestHeader *
       request_header__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RequestHeader *)
     protobuf_c_message_unpack (&request_header__descriptor,
                                allocator, len, data);
}
void   request_header__free_unpacked
                     (RequestHeader *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &request_header__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   exfiltration_request__init
                     (ExfiltrationRequest         *message)
{
  static const ExfiltrationRequest init_value = EXFILTRATION_REQUEST__INIT;
  *message = init_value;
}
size_t exfiltration_request__get_packed_size
                     (const ExfiltrationRequest *message)
{
  assert(message->base.descriptor == &exfiltration_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t exfiltration_request__pack
                     (const ExfiltrationRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &exfiltration_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t exfiltration_request__pack_to_buffer
                     (const ExfiltrationRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &exfiltration_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ExfiltrationRequest *
       exfiltration_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ExfiltrationRequest *)
     protobuf_c_message_unpack (&exfiltration_request__descriptor,
                                allocator, len, data);
}
void   exfiltration_request__free_unpacked
                     (ExfiltrationRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &exfiltration_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   infiltration_request__init
                     (InfiltrationRequest         *message)
{
  static const InfiltrationRequest init_value = INFILTRATION_REQUEST__INIT;
  *message = init_value;
}
size_t infiltration_request__get_packed_size
                     (const InfiltrationRequest *message)
{
  assert(message->base.descriptor == &infiltration_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t infiltration_request__pack
                     (const InfiltrationRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &infiltration_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t infiltration_request__pack_to_buffer
                     (const InfiltrationRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &infiltration_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
InfiltrationRequest *
       infiltration_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (InfiltrationRequest *)
     protobuf_c_message_unpack (&infiltration_request__descriptor,
                                allocator, len, data);
}
void   infiltration_request__free_unpacked
                     (InfiltrationRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &infiltration_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   read_dir_request__init
                     (ReadDirRequest         *message)
{
  static const ReadDirRequest init_value = READ_DIR_REQUEST__INIT;
  *message = init_value;
}
size_t read_dir_request__get_packed_size
                     (const ReadDirRequest *message)
{
  assert(message->base.descriptor == &read_dir_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t read_dir_request__pack
                     (const ReadDirRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &read_dir_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t read_dir_request__pack_to_buffer
                     (const ReadDirRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &read_dir_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ReadDirRequest *
       read_dir_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ReadDirRequest *)
     protobuf_c_message_unpack (&read_dir_request__descriptor,
                                allocator, len, data);
}
void   read_dir_request__free_unpacked
                     (ReadDirRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &read_dir_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   suicide_request__init
                     (SuicideRequest         *message)
{
  static const SuicideRequest init_value = SUICIDE_REQUEST__INIT;
  *message = init_value;
}
size_t suicide_request__get_packed_size
                     (const SuicideRequest *message)
{
  assert(message->base.descriptor == &suicide_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t suicide_request__pack
                     (const SuicideRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &suicide_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t suicide_request__pack_to_buffer
                     (const SuicideRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &suicide_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SuicideRequest *
       suicide_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SuicideRequest *)
     protobuf_c_message_unpack (&suicide_request__descriptor,
                                allocator, len, data);
}
void   suicide_request__free_unpacked
                     (SuicideRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &suicide_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCEnumValue request_header__type__enum_values_by_number[4] =
{
  { "SUICIDE", "REQUEST_HEADER__TYPE__SUICIDE", 0 },
  { "EXF_FILE", "REQUEST_HEADER__TYPE__EXF_FILE", 1 },
  { "INF_FILE", "REQUEST_HEADER__TYPE__INF_FILE", 2 },
  { "READ_DIR", "REQUEST_HEADER__TYPE__READ_DIR", 3 },
};
static const ProtobufCIntRange request_header__type__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex request_header__type__enum_values_by_name[4] =
{
  { "EXF_FILE", 1 },
  { "INF_FILE", 2 },
  { "READ_DIR", 3 },
  { "SUICIDE", 0 },
};
const ProtobufCEnumDescriptor request_header__type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "requestHeader.Type",
  "Type",
  "RequestHeader__Type",
  "",
  4,
  request_header__type__enum_values_by_number,
  4,
  request_header__type__enum_values_by_name,
  1,
  request_header__type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor request_header__field_descriptors[2] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(RequestHeader, type),
    &request_header__type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "size",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(RequestHeader, size),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned request_header__field_indices_by_name[] = {
  1,   /* field[1] = size */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange request_header__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor request_header__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "requestHeader",
  "RequestHeader",
  "RequestHeader",
  "",
  sizeof(RequestHeader),
  2,
  request_header__field_descriptors,
  request_header__field_indices_by_name,
  1,  request_header__number_ranges,
  (ProtobufCMessageInit) request_header__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor exfiltration_request__field_descriptors[1] =
{
  {
    "path",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ExfiltrationRequest, path),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned exfiltration_request__field_indices_by_name[] = {
  0,   /* field[0] = path */
};
static const ProtobufCIntRange exfiltration_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor exfiltration_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "exfiltrationRequest",
  "ExfiltrationRequest",
  "ExfiltrationRequest",
  "",
  sizeof(ExfiltrationRequest),
  1,
  exfiltration_request__field_descriptors,
  exfiltration_request__field_indices_by_name,
  1,  exfiltration_request__number_ranges,
  (ProtobufCMessageInit) exfiltration_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor infiltration_request__field_descriptors[3] =
{
  {
    "perm",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(InfiltrationRequest, perm),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "path",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(InfiltrationRequest, path),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "content",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(InfiltrationRequest, content),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned infiltration_request__field_indices_by_name[] = {
  2,   /* field[2] = content */
  1,   /* field[1] = path */
  0,   /* field[0] = perm */
};
static const ProtobufCIntRange infiltration_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor infiltration_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "infiltrationRequest",
  "InfiltrationRequest",
  "InfiltrationRequest",
  "",
  sizeof(InfiltrationRequest),
  3,
  infiltration_request__field_descriptors,
  infiltration_request__field_indices_by_name,
  1,  infiltration_request__number_ranges,
  (ProtobufCMessageInit) infiltration_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor read_dir_request__field_descriptors[1] =
{
  {
    "path",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ReadDirRequest, path),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned read_dir_request__field_indices_by_name[] = {
  0,   /* field[0] = path */
};
static const ProtobufCIntRange read_dir_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor read_dir_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "readDirRequest",
  "ReadDirRequest",
  "ReadDirRequest",
  "",
  sizeof(ReadDirRequest),
  1,
  read_dir_request__field_descriptors,
  read_dir_request__field_indices_by_name,
  1,  read_dir_request__number_ranges,
  (ProtobufCMessageInit) read_dir_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define suicide_request__field_descriptors NULL
#define suicide_request__field_indices_by_name NULL
#define suicide_request__number_ranges NULL
const ProtobufCMessageDescriptor suicide_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "suicideRequest",
  "SuicideRequest",
  "SuicideRequest",
  "",
  sizeof(SuicideRequest),
  0,
  suicide_request__field_descriptors,
  suicide_request__field_indices_by_name,
  0,  suicide_request__number_ranges,
  (ProtobufCMessageInit) suicide_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
