# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: request.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rrequest.proto\"\x7f\n\rrequestHeader\x12!\n\x04type\x18\x01 \x02(\x0e\x32\x13.requestHeader.Type\x12\x0c\n\x04size\x18\x02 \x02(\x04\"=\n\x04Type\x12\x0b\n\x07SUICIDE\x10\x00\x12\x0c\n\x08\x45XF_FILE\x10\x01\x12\x0c\n\x08INF_FILE\x10\x02\x12\x0c\n\x08READ_DIR\x10\x03\"#\n\x13\x65xfiltrationRequest\x12\x0c\n\x04path\x18\x01 \x02(\t\"B\n\x13infiltrationRequest\x12\x0c\n\x04perm\x18\x01 \x02(\r\x12\x0c\n\x04path\x18\x02 \x02(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x02(\x0c\"\x1e\n\x0ereadDirRequest\x12\x0c\n\x04path\x18\x01 \x02(\t')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'request_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUESTHEADER._serialized_start=17
  _REQUESTHEADER._serialized_end=144
  _REQUESTHEADER_TYPE._serialized_start=83
  _REQUESTHEADER_TYPE._serialized_end=144
  _EXFILTRATIONREQUEST._serialized_start=146
  _EXFILTRATIONREQUEST._serialized_end=181
  _INFILTRATIONREQUEST._serialized_start=183
  _INFILTRATIONREQUEST._serialized_end=249
  _READDIRREQUEST._serialized_start=251
  _READDIRREQUEST._serialized_end=281
# @@protoc_insertion_point(module_scope)
