# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: response.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eresponse.proto\"7\n\x0eresponseHeader\x12\x17\n\x06status\x18\x01 \x02(\x0e\x32\x07.Status\x12\x0c\n\x04size\x18\x02 \x02(\x04\"\'\n\x14\x45xfiltrationResponse\x12\x0f\n\x07\x63ontent\x18\x01 \x02(\x0c\"\x16\n\x14InfiltrationResponse\"}\n\x0fReadDirResponse\x12*\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x19.ReadDirResponse.DirEntry\x1a>\n\x08\x44irEntry\x12\r\n\x05inode\x18\x01 \x02(\r\x12\x11\n\tfile_type\x18\x02 \x02(\r\x12\x10\n\x08pathname\x18\x03 \x02(\t*t\n\x06Status\x12\x08\n\x04GOOD\x10\x00\x12\x0e\n\nOPEN_ERROR\x10\x01\x12\x0e\n\nREAD_ERROR\x10\x02\x12\x0f\n\x0bWRITE_ERROR\x10\x03\x12\x0e\n\nSTAT_ERROR\x10\x04\x12\x0c\n\x08NOT_FILE\x10\x05\x12\x11\n\rNOT_DIRECTORY\x10\x06')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'response_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STATUS._serialized_start=267
  _STATUS._serialized_end=383
  _RESPONSEHEADER._serialized_start=18
  _RESPONSEHEADER._serialized_end=73
  _EXFILTRATIONRESPONSE._serialized_start=75
  _EXFILTRATIONRESPONSE._serialized_end=114
  _INFILTRATIONRESPONSE._serialized_start=116
  _INFILTRATIONRESPONSE._serialized_end=138
  _READDIRRESPONSE._serialized_start=140
  _READDIRRESPONSE._serialized_end=265
  _READDIRRESPONSE_DIRENTRY._serialized_start=203
  _READDIRRESPONSE_DIRENTRY._serialized_end=265
# @@protoc_insertion_point(module_scope)
